replicaCount: 2

podAnnotations:
  linkerd.io/inject: enabled

image:
  repository: registry.happytravel.com/takato
  tag: latest
  pullPolicy: Always
imagePullSecrets:
  - name: travel-registry
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: pms-dev.happytravel.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: happytravel-tls
     hosts:
       - pms-dev.happytravel.com

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 25m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - takato
      topologyKey: "kubernetes.io/hostname"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80